name: test

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - id: find
        run: |
          echo 'result<<EOF' | tee -a "$GITHUB_OUTPUT"
          find . \( -name '*.sh' -o -name '*.bash' \) -print0 | xargs -0 echo | tee -a "$GITHUB_OUTPUT"
          echo 'EOF' | tee -a "$GITHUB_OUTPUT"
      - uses: docker://koalaman/shellcheck:stable
        with:
          args: ${{ steps.find.outputs.result }}
  test:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
        manager:
          - bun
          - pnpm
          - yarn
          # - yarn-berry
          - npm
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
    steps:
      - if: matrix.os == 'windows-latest'
        run: git config --global core.autocrlf false
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - if: matrix.manager == 'npm' || matrix.manager == 'yarn'
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/*
      - if: matrix.manager == 'bun'
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
        with:
          bun-version: latest
      - if: matrix.manager == 'pnpm'
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
        with:
          version: latest
      - run: make install
      - run: |
          case '${{ matrix.manager }}' in
            bun)
              touch bun.lock
              ;;
            pnpm)
              touch pnpm-lock.yml
              ;;
            yarn)
              touch yarn.lock
              ;;
            npm)
              touch package-lock.json
              ;;
          esac
      - run: make test
  test-result:
    if: >
      !cancelled()
      && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository)
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - run: test '${{ needs.lint.result }}' != 'failure' && test '${{ needs.test.result }}' != 'failure'
